//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BreweryBucketList
{
    using System;
    using System.Collections.Generic;
    
    public partial class Brewery
    {
        public int BreweryID { get; set; }
        public string BreweryName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public int CountyID { get; set; }
        public string Website { get; set; }
    
        public virtual County County { get; set; }
        public virtual Order Order { get; set; }
    }
}
