//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BreweryBucketList
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public int CustomerID { get; set; }
        public int BreweryID { get; set; }
        public Nullable<bool> visited { get; set; }
        public string comments { get; set; }
    
        public virtual Brewery Brewery { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
